[package]
name = "sway-voice-type"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
crossbeam-channel = "0.5"
cpal = "0.15"
evdev = "0.12"
hound = "3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
which = "6"
uuid = { version = "1.0", features = ["v4"] }

ksni = "0.2"
whisper-rs = "0.15"
